// AUTO-GENERATED by scripts/migrate-public-site-assets.mjs — do not edit by hand.
// Maps public-site asset slugs to Supabase Storage CDN URLs.
//
// Each entry has the original + four WebP derivatives (320 / 600 / 1200 / 2000 width).
// <OptimizedImage src="<slug>" /> renders an <img srcset> driven by these.
// asset(slug) returns the original; asset(slug, "w600") picks a specific size.

export interface AssetSources {
  original: string;
  w320: string;
  w600: string;
  w1200: string;
  w2000: string;
}

export const ASSET_MANIFEST: Record<string, AssetSources> = {
  "band-hero": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band-hero.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band-hero.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band-hero.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band-hero.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band-hero.webp"
  },
  "band/group-laughing": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/group-laughing.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/group-laughing.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/group-laughing.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/group-laughing.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/group-laughing.webp"
  },
  "band/group-portrait": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/group-portrait.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/group-portrait.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/group-portrait.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/group-portrait.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/group-portrait.webp"
  },
  "band/group-waterfront-1": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/group-waterfront-1.webp",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/group-waterfront-1.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/group-waterfront-1.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/group-waterfront-1.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/group-waterfront-1.webp"
  },
  "band/group-waterfront-2": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/group-waterfront-2.webp",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/group-waterfront-2.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/group-waterfront-2.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/group-waterfront-2.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/group-waterfront-2.webp"
  },
  "band/group-waterfront-3": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/group-waterfront-3.webp",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/group-waterfront-3.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/group-waterfront-3.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/group-waterfront-3.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/group-waterfront-3.webp"
  },
  "band/group-waterfront-4": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/group-waterfront-4.webp",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/group-waterfront-4.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/group-waterfront-4.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/group-waterfront-4.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/group-waterfront-4.webp"
  },
  "band/jazz-trio-1": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/jazz-trio-1.webp",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/jazz-trio-1.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/jazz-trio-1.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/jazz-trio-1.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/jazz-trio-1.webp"
  },
  "band/jazz-trio-2": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/jazz-trio-2.webp",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/jazz-trio-2.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/jazz-trio-2.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/jazz-trio-2.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/jazz-trio-2.webp"
  },
  "band/live-dj-sax": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/live-dj-sax.webp",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/live-dj-sax.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/live-dj-sax.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/live-dj-sax.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/live-dj-sax.webp"
  },
  "band/live-performance-1": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/live-performance-1.png",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/live-performance-1.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/live-performance-1.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/live-performance-1.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/live-performance-1.webp"
  },
  "band/member-1": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/member-1.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/member-1.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/member-1.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/member-1.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/member-1.webp"
  },
  "band/member-2": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/member-2.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/member-2.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/member-2.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/member-2.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/member-2.webp"
  },
  "band/member-3": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/member-3.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/member-3.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/member-3.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/member-3.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/member-3.webp"
  },
  "band/member-4": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/member-4.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/member-4.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/member-4.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/member-4.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/member-4.webp"
  },
  "band/member-5": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/member-5.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/member-5.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/member-5.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/member-5.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/member-5.webp"
  },
  "band/member-6": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/member-6.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/member-6.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/member-6.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/member-6.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/member-6.webp"
  },
  "band/portrait-player1-a": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/portrait-player1-a.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/portrait-player1-a.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/portrait-player1-a.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/portrait-player1-a.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/portrait-player1-a.webp"
  },
  "band/portrait-player1-b": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/portrait-player1-b.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/portrait-player1-b.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/portrait-player1-b.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/portrait-player1-b.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/portrait-player1-b.webp"
  },
  "band/portrait-player2-a": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/portrait-player2-a.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/portrait-player2-a.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/portrait-player2-a.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/portrait-player2-a.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/portrait-player2-a.webp"
  },
  "band/portrait-player3-a": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/portrait-player3-a.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/portrait-player3-a.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/portrait-player3-a.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/portrait-player3-a.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/portrait-player3-a.webp"
  },
  "band/portrait-player4-a": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/portrait-player4-a.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/portrait-player4-a.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/portrait-player4-a.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/portrait-player4-a.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/portrait-player4-a.webp"
  },
  "band/portrait-player4-b": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/portrait-player4-b.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/portrait-player4-b.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/portrait-player4-b.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/portrait-player4-b.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/portrait-player4-b.webp"
  },
  "band/portrait-player5-a": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/portrait-player5-a.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/portrait-player5-a.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/portrait-player5-a.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/portrait-player5-a.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/portrait-player5-a.webp"
  },
  "band/portrait-player5-b": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/portrait-player5-b.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/portrait-player5-b.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/portrait-player5-b.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/portrait-player5-b.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/portrait-player5-b.webp"
  },
  "band/setup-tent": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/setup-tent.png",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/setup-tent.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/setup-tent.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/setup-tent.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/setup-tent.webp"
  },
  "band/setup-waterfront": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/setup-waterfront.png",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/setup-waterfront.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/setup-waterfront.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/setup-waterfront.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/setup-waterfront.webp"
  },
  "band/special-event-dancer": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/band/special-event-dancer.webp",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/band/special-event-dancer.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/band/special-event-dancer.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/band/special-event-dancer.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/band/special-event-dancer.webp"
  },
  "gallery-1": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/gallery-1.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/gallery-1.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/gallery-1.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/gallery-1.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/gallery-1.webp"
  },
  "gallery-2": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/gallery-2.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/gallery-2.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/gallery-2.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/gallery-2.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/gallery-2.webp"
  },
  "gallery-3": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/gallery-3.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/gallery-3.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/gallery-3.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/gallery-3.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/gallery-3.webp"
  },
  "gallery-4": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/gallery-4.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/gallery-4.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/gallery-4.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/gallery-4.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/gallery-4.webp"
  },
  "gallery-5": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/gallery-5.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/gallery-5.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/gallery-5.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/gallery-5.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/gallery-5.webp"
  },
  "hero-band": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/hero-band.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/hero-band.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/hero-band.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/hero-band.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/hero-band.webp"
  },
  "instagram/ig-1": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/instagram/ig-1.png",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/instagram/ig-1.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/instagram/ig-1.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/instagram/ig-1.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/instagram/ig-1.webp"
  },
  "instagram/ig-2": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/instagram/ig-2.png",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/instagram/ig-2.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/instagram/ig-2.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/instagram/ig-2.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/instagram/ig-2.webp"
  },
  "instagram/ig-3": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/instagram/ig-3.png",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/instagram/ig-3.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/instagram/ig-3.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/instagram/ig-3.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/instagram/ig-3.webp"
  },
  "instagram/ig-4": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/instagram/ig-4.png",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/instagram/ig-4.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/instagram/ig-4.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/instagram/ig-4.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/instagram/ig-4.webp"
  },
  "instagram/ig-5": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/instagram/ig-5.png",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/instagram/ig-5.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/instagram/ig-5.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/instagram/ig-5.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/instagram/ig-5.webp"
  },
  "instagram/ig-6": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/instagram/ig-6.png",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/instagram/ig-6.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/instagram/ig-6.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/instagram/ig-6.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/instagram/ig-6.webp"
  },
  "instagram/ig-7": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/instagram/ig-7.png",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/instagram/ig-7.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/instagram/ig-7.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/instagram/ig-7.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/instagram/ig-7.webp"
  },
  "instagram/ig-8": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/instagram/ig-8.png",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/instagram/ig-8.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/instagram/ig-8.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/instagram/ig-8.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/instagram/ig-8.webp"
  },
  "venues/avam-1": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/avam-1.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/avam-1.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/avam-1.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/avam-1.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/avam-1.webp"
  },
  "venues/belvedere-1": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/belvedere-1.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/belvedere-1.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/belvedere-1.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/belvedere-1.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/belvedere-1.webp"
  },
  "venues/belvedere-2": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/belvedere-2.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/belvedere-2.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/belvedere-2.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/belvedere-2.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/belvedere-2.webp"
  },
  "venues/bo-railroad-1": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/bo-railroad-1.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/bo-railroad-1.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/bo-railroad-1.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/bo-railroad-1.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/bo-railroad-1.webp"
  },
  "venues/bo-railroad-2": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/bo-railroad-2.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/bo-railroad-2.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/bo-railroad-2.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/bo-railroad-2.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/bo-railroad-2.webp"
  },
  "venues/cloisters-1": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/cloisters-1.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/cloisters-1.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/cloisters-1.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/cloisters-1.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/cloisters-1.webp"
  },
  "venues/cloisters-2": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/cloisters-2.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/cloisters-2.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/cloisters-2.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/cloisters-2.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/cloisters-2.webp"
  },
  "venues/cylburn-1": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/cylburn-1.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/cylburn-1.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/cylburn-1.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/cylburn-1.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/cylburn-1.webp"
  },
  "venues/cylburn-2": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/cylburn-2.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/cylburn-2.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/cylburn-2.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/cylburn-2.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/cylburn-2.webp"
  },
  "venues/evergreen-1": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/evergreen-1.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/evergreen-1.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/evergreen-1.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/evergreen-1.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/evergreen-1.webp"
  },
  "venues/evergreen-2": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/evergreen-2.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/evergreen-2.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/evergreen-2.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/evergreen-2.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/evergreen-2.webp"
  },
  "venues/four-seasons-1": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/four-seasons-1.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/four-seasons-1.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/four-seasons-1.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/four-seasons-1.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/four-seasons-1.webp"
  },
  "venues/four-seasons-2": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/four-seasons-2.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/four-seasons-2.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/four-seasons-2.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/four-seasons-2.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/four-seasons-2.webp"
  },
  "venues/legg-mason-1": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/legg-mason-1.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/legg-mason-1.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/legg-mason-1.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/legg-mason-1.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/legg-mason-1.webp"
  },
  "venues/peabody-1": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/peabody-1.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/peabody-1.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/peabody-1.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/peabody-1.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/peabody-1.webp"
  },
  "venues/peabody-2": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/peabody-2.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/peabody-2.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/peabody-2.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/peabody-2.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/peabody-2.webp"
  },
  "venues/pendry-1": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/pendry-1.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/pendry-1.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/pendry-1.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/pendry-1.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/pendry-1.webp"
  },
  "venues/pendry-2": {
    "original": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/venues/pendry-2.jpg",
    "w320": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w320/venues/pendry-2.webp",
    "w600": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w600/venues/pendry-2.webp",
    "w1200": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w1200/venues/pendry-2.webp",
    "w2000": "https://mbqyznttpvebahgygsbx.supabase.co/storage/v1/object/public/visual-assets/public-site/derivatives/w2000/venues/pendry-2.webp"
  }
} as const;

export type AssetSlug = keyof typeof ASSET_MANIFEST;
export type AssetSize = "original" | "w320" | "w600" | "w1200" | "w2000";
