-- Imports the song catalogue (Accumulated Songs + Songs to Learn) from
-- Josh's practice-log spreadsheet bottom reference table.
INSERT INTO practice_songs (title, artist, key, status, notes, times_practiced) VALUES
  ('Mirror Mirror', '', '', 'learned', '', 0),
  ('Armandos Rhumba', '', '', 'learned', '', 0),
  ('Along Came Betty', '', '', 'learned', '', 0),
  ('Jitterbug Waltz', '', '', 'learned', '', 0),
  ('On a Clear Day', '', '', 'learned', '', 0),
  ('Love & Peace', '', '', 'learned', '', 0),
  ('Emily', '', '', 'learned', '', 0),
  ('My One and Only Love', '', '', 'learned', '', 0),
  ('Stablemates', '', '', 'learned', '', 0),
  ('My Mans Gone Now', '', '', 'learned', '', 0),
  ('St. Thomas', '', '', 'learned', '', 0),
  ('Red Barron', '', '', 'learned', '', 0),
  ('After You''ve Gone', '', '', 'learned', '', 0),
  ('Blue in Green', '', '', 'learned', '', 0),
  ('Wii Sports', '', '', 'learned', '', 0),
  ('Blues for Alice', '', '', 'learned', '', 0),
  ('Afternoon in Paris', '', '', 'learned', '', 0),
  ('Airegin', '', '', 'learned', '', 0),
  ('Fingerprints', '', '', 'learned', '', 0),
  ('Ugetsu', '', '', 'learned', '', 0),
  ('Skylark', '', '', 'learned', '', 0),
  ('Freight Trane', '', '', 'learned', '', 0),
  ('Comrad Conrad', '', '', 'learned', '', 0),
  ('Confirmation', '', '', 'learned', '', 0),
  ('Scrapple from the Apple', '', '', 'learned', '', 0),
  ('Out of Time', '', '', 'learned', '', 0),
  ('I Keep Forgetting', '', '', 'learned', '', 0),
  ('Nothing Can Come Between Us', '', '', 'learned', '', 0),
  ('After Light Night', '', '', 'learned', '', 0),
  ('Passion (Pink Panther)', '', '', 'learned', '', 0),
  ('Passion Dance', '', '', 'learned', '', 0),
  ('Pure Imagination', '', '', 'learned', '', 0),
  ('Actual Proof', '', '', 'learned', '', 0),
  ('Celia', '', '', 'learned', '', 0),
  ('Whippersnapper', '', '', 'learned', '', 0),
  ('One Finger Snap', '', '', 'learned', '', 0),
  ('Dexterity', '', '', 'learned', '', 0),
  ('I''ve Grown Accustomed to Your Face', '', '', 'learned', '', 0),
  ('Valdez Off Crenshaw', '', '', 'to_learn', '', 0),
  ('Day by Day', '', '', 'to_learn', '', 0),
  ('Sometime Ago', '', '', 'to_learn', '', 0);
